# Generated by Django 5.1 on 2024-08-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_todo_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
